name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleet:
          [
            blues_wireless/notecard-aarch64,
            blues_wireless/notecard-armv7hf,
            blues_wireless/notecard-amd64,
          ]

    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.10.7
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          environment: balena-cloud.com
          fleet: ${{ matrix.fleet }}
          versionbot: true
